#!/bin/bash

SERVER="${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/echo_service"
URL="http://localhost:8011/echo"
LOG_FILE="echo.log"
THREAD_COUNT=4

$SERVER --url $URL --threads $THREAD_COUNT &>$LOG_FILE &
SERVER_PID=$!

# wait for server start
sleep 2


WRK_EXE="${CMAKE_SOURCE_DIR}/third-party/wrk/wrk"
WRK_SCRIPT="${ECHO_STRESS_WRK_SCRIPT}"


$WRK_EXE -t8 -c16 -d1m -s $WRK_SCRIPT --timeout 10s $URL


# and stop the server
kill -s INT $SERVER_PID
wait
